### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by willemneal** [near/workspaces-rs#63] opened 2022-01-25 21:58 UTC
Here is a repo I made and used workspaces-rs to test with: https://github.com/TENK-DAO/vip-list

For me the single test take 200s to run on sandbox.  Compared to ~11s to run the JS version.

> `yarn`

>`yarn test` # runs rust

> `yarn ava` # runs js

Do I have something wrong with my setup?  I gather that for other people 200s is not the norm.

**Comment by itegulov** [comment] 2022-01-25 22:07
Can you try running your repo with master version of workspaces? Specifically with [this](https://github.com/near/workspaces-rs/pull/60) PR in. I used to see performance issues too that were being caused by the race condition from #60 in my case.

**Comment by willemneal** [comment] 2022-01-25 22:40
Thanks now at ~11s too!

**Comment by itegulov** [comment] 2022-01-25 23:13
@willemneal Nice! Can we close this then?

**Comment by willemneal** [comment] 2022-01-25 23:31
Yep!

**Closed** 2022-01-25 23:34 UTC
