### ISSUE TITLE
Making view call with invalid params returns bad error

### ISSUE THREAD

**Issue by austinabell** [near/workspaces-rs#226] opened 2022-11-02 01:43 UTC
Currently, if you call a method with invalid parameter serialization, you get an error like this:

```
Error: error while parsing method call result: [data did not match any variant of untagged enum QueryResponseKind]
thread 'ws_tests::test_approve' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: the test returned a termination value with a non-zero status code (1) which indicates a failure', /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/test/src/lib.rs:184:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Which isn't helpful to debug that it was the parameters that were of the wrong format.

I haven't dug into if this error is at the client level or workspaces, but feel free to move the issue if it's in the wrong place!

**Comment by ChaoticTempest** [comment] 2022-11-11 00:06
@miraclx looks like `data did not match any variant of untagged enum QueryResponseKind` is still an issue. Confirmed on my end that it's also an issue when passing in an invalid function name:

```rust
    let status_msg = worker.dev_deploy(...).await?;
    let msg: String = status_msg.view("view_status")
        .args_json(json!({
            "account_id": status_msg.id(),
        }))
        .await?
        .json()?;
```

**Comment by miraclx** [comment] 2022-11-11 00:07
I'm looking into it.

**Comment by miraclx** [comment] 2022-11-11 01:40
Nifty case, but I found out why. `&RpcMethod` was handling responses differently from `RpcMethod`s.

Patched in https://github.com/near/near-jsonrpc-client-rs/pull/114

**Comment by miraclx** [comment] 2022-11-12 01:49
@ChaoticTempest, pending the release of `workspaces@0.7.0`, would it help to release a patch version of `0.6` that includes this fix?

**Comment by ChaoticTempest** [comment] 2022-11-12 02:34
it's not too big of a bug, but checking stats on crates.io shows a lot of users still on 0.4.1 and 0.5.0 which might also be worth adding to. I'll evaluate that on monday, but it's definitely worth adding a 0.6.1 release

**Comment by ChaoticTempest** [comment] 2022-11-15 22:40
So decided not to backport to 0.4* and 0.5* since the upgrade to near-jsonrpc-client 0.4.1 requires a breaking change on workspaces API, but at least 0.6.1 has been released with it

**Closed by ChaoticTempest** 2022-11-15 22:40 UTC
