### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by mrLSD** [near/workspaces-rs#252] opened 2022-12-09 01:01 UTC
When running github CI have got a lot of errors:
> No such file or directory

Github action output:
https://github.com/aurora-is-near/aurora-eth-connector/actions/runs/3653316774/jobs/6172646267

**Comment by ChaoticTempest** [comment] 2022-12-09 22:49
These are generic unable to find file kind of errors which workspaces doesn't really manage where you point to since underneath are pure `File::open` calls. Check to make sure the file paths are correct, but otherwise closing this one for now. Feel free to reopen if you think there's something up on workspaces side

**Comment by mrLSD** [comment] 2022-12-10 00:52
It's related to the sandbox file no exist.

Proof: https://github.com/aurora-is-near/aurora-eth-connector/actions/runs/3661845365/jobs/6190451337

It is the same as: #193
(I know it was fixed. But for some reason with v0.6 release the issue appeared again)

**Comment by mrLSD** [comment] 2022-12-10 00:57
@ChaoticTempest , I do not have access right to reopen that issue. So will open a new one.

**Comment by ChaoticTempest** [comment] 2022-12-10 01:00
I'll reopen it just so we don't lose further context

**Comment by ChaoticTempest** [comment] 2022-12-10 01:36
@mrLSD It's really hard to narrow down what the issue is since it's not failing for me and I can't reproduce. But I think one way to force out of the situation is by calling into `near_sandbox_utils::ensure_sandbox_bin()?;` before `workspaces::sandbox()` to ensure that the binary gets installed. It should error out on that call and should provide more details about why it didn't get installed

**Comment by mrLSD** [comment] 2022-12-10 02:28
Did it, but seems it doesn't provide additional info at all:
https://github.com/aurora-is-near/aurora-eth-connector/actions/runs/3662216074/jobs/6191149730

**Closed** 2023-01-11 00:22 UTC
